- .bowerrc
- .gitignore
- bower.json
- src/materials/atoms/buttons/button-radius.html
- src/materials/molecules/language-actions.html
- src/materials/organisms/top-bar.html
- src/materials/organisms/welcome-block.html
- src/materials/organisms/welcome-header.html
- src/views/pages/home.html
Markup patterns are available for the Welcome/Home page.
> Created markup patterns for welcome/home page and added bower components

- dist/molecules.html
- dist/pages/eligibility-start--error.html
- dist/pages/eligibility-start.html
- pages/eligibility-start.html
- src/materials/molecules/forms/select--occupancy.html
Added the markup for the Age Eligibility feature.
> [#108640456] Added markup to pattern library for Age Eligibility feature

- src/materials/organisms/property-card--closed.html
- src/materials/organisms/property-card--matched.html
- src/materials/organisms/property-card--not-matched.html
- src/materials/organisms/property-card--results.html
- src/materials/organisms/property-card.html
In reference to story: https://www.pivotaltracker.com/story/show/112103893
> [#112103893] - Implement alt for listing image and link

- package.json
- src/assets/toolkit/scripts/toolkit.js
- src/assets/toolkit/styles/utilities/_all.scss
- src/assets/toolkit/styles/utilities/_animations.scss
- src/materials/molecules/components/feed-item.html
- src/materials/molecules/navigation/top-bar--account.html
- src/views/layouts/center.html
- src/views/pages/account/account-applications.html
> [ng-animate] adding experiment with ngAnimate on ng-hide

- src/assets/toolkit/styles/templates/_print.scss
@slowbot @menslow 
needed for story: https://www.pivotaltracker.com/story/show/129736963
> Updated css to show all hidden elements in print mode

- package.json
- src/assets/toolkit/scripts/form-validation-controller.js
- src/assets/toolkit/scripts/toolkit.js
- src/assets/toolkit/styles/_settings.scss
- src/assets/toolkit/styles/components/_app-card.scss
- src/assets/toolkit/styles/components/_inputs.scss
- src/assets/toolkit/styles/components/_toggler.scss
- src/materials/molecules/forms/checkbox-group--block.html
- src/materials/templates/angular-income-form.html
- src/views/pages/angular_forms/form-validation.html
- src/views/pages/application/application-preferences--more.html
- src/views/pages/application/application-preferences--nested.html
- src/views/pages/application/application-preferences--nrhp.html
- src/views/pages/application/application-programs--nested.html
https://sf-dahlia-pl-nrhp.herokuapp.com/application/application-preferences--nrhp.html
> Chores/live in neighborhood #139505365

- src/materials/molecules/forms/checkbox-group--block.html
- src/materials/molecules/forms/checkbox-group.html
- src/materials/molecules/forms/icon-input.html
- src/materials/molecules/forms/radio-group--block.html
- src/materials/molecules/forms/radio-group.html
- src/materials/molecules/navigation/top-bar.html
- src/materials/organisms/modal--small.html
- src/materials/organisms/modal.html
- src/materials/organisms/property-card.html
- src/materials/organisms/results-buckets--search.html
Merged into wrong branch. Reverts Exygy/sf-dahlia-pattern-library#39
> Revert "Features/update html pattern library #143063197"

- src/assets/toolkit/styles/base/_button.scss
- src/assets/toolkit/styles/components/_modal.scss
Tied to [PR #769](https://github.com/Exygy/sf-dahlia-web/pull/769) on the web app
> Features/modals not popups #141341079

- src/assets/fabricator/styles/fabricator.scss
- src/assets/fabricator/styles/utilities/_colors.scss
- src/assets/fabricator/styles/utilities/borders.scss
- src/assets/fabricator/styles/utilities/mixins.scss
- src/assets/fabricator/styles/utilities/positioning.scss
- src/assets/fabricator/styles/utilities/spacing.scss
- src/data/utilities.yml
- src/materials/utilities/borders.html
- src/materials/utilities/positioning.html
- src/materials/utilities/spacing.html
- src/materials/utility-mixins/image-replace.html
- src/materials/utility-mixins/linear-gradient.html
- src/materials/utility-mixins/link-wrap.html
- src/materials/utility-mixins/overlay-image.html
- src/materials/utility-mixins/sr-only.html
- src/materials/utility-mixins/triangle.html
- src/views/layouts/default.html
- src/views/utilities.html
- src/views/utility-mixins.html
This PR isn't ready yet, but creating it now so we can diff the branch against master.
> Features/utilities documentation #143062915

- src/assets/toolkit/styles/molecules/_progress-nav.scss
- src/assets/toolkit/styles/molecules/_status-header.scss
- src/assets/toolkit/styles/molecules/_top-bar.scss
- src/assets/toolkit/styles/molecules/_translate-bar.scss
- src/assets/toolkit/styles/organisms/_footer.scss
- src/materials/molecules/navigation/top-bar--translation.html
- src/materials/molecules/navigation/top-bar.html
- src/views/pages/home-translations.html
Fixing main navigation for longer menu items with flexbox
Fixing short form navigation spacing
Adjustments to translation bar styles
> Flexbox nav solution for top bar

- src/assets/toolkit/styles/molecules/_content-stat.scss
> Bugs/waitlist numbers run into text #151338954

- src/assets/toolkit/styles/atoms/_tables.scss
- src/assets/toolkit/styles/molecules/_name-logo.scss
- src/assets/toolkit/styles/molecules/_react-tables.scss
- src/assets/toolkit/styles/molecules/_top-bar.scss
- src/assets/toolkit/styles/organisms/_center-body.scss
- src/assets/toolkit/styles/toolkit-lap.scss
- src/assets/toolkit/styles/utilities/_grid.scss
- src/assets/toolkit/styles/utilities/_spacing.scss
- src/materials/atoms/tables/table--features.html
- Migrating react table styles from LAP into pattern library
- Removing visual styles and refactoring structural classes
- Updating base table styles with extends for core elements
- Adding extends to map base table styles to react table
- Adding utility classes for left and right text alignment
https://github.com/Exygy/sf-dahlia-lap/pull/2
> Adding React Table styles to Pattern Library

- src/assets/toolkit/styles/utilities/_print.scss
Goes with this web app PR: https://github.com/Exygy/sf-dahlia-web/pull/976.
> Bugs/housing counselor page printing incorrectly #152625990

- src/assets/fabricator/styles/utilities/spacing.scss
- src/assets/toolkit/styles/_settings.scss
- src/assets/toolkit/styles/atoms/_all.scss
- src/assets/toolkit/styles/atoms/_button.scss
- src/assets/toolkit/styles/atoms/_dropdowns.scss
- src/assets/toolkit/styles/organisms/_page-accordion.scss
- src/assets/toolkit/styles/toolkit-base.scss
- src/assets/toolkit/styles/toolkit-lap.scss
- src/assets/toolkit/styles/toolkit.scss
- src/data/buttons.yml
- src/materials/01-atoms/buttons/button-dropdown-multiselect.html
- src/materials/01-atoms/buttons/button-dropdown-state.html
- src/materials/01-atoms/buttons/button-dropdown.html
- src/materials/01-atoms/buttons/button-icon.html
- src/materials/01-atoms/forms/checkbox.html
- src/views/layouts/includes/f-item-content.html
**States**
- adding color map for states: approved, processing, withdrawn, disqualified, leased, appealed, waitlisted
- adding variant classes is-"variant" for dropdown-menu_items
**Variants**
- adding checkboxes for multi select option
- adding separator to divide sets of list items
**Aria:**
- tab-index=-1 to dropdown menu
- aria-expanded=true/false on button
- aria-hidden=true/false on expanded menu
- aria-hidden=true to dropdown icon
- aria-selected=true/false for list item
- role="listbox" instead of "menu" to allow for aria-multiselectable to be added
- role="option" to each list item,
- role="separator" for divider
- added aria-activedescendant for focusable child elements
**Global updates to button conventions**
- can use either has-icon or has-icon--right and not both in …
> Dropdown Button

- src/assets/toolkit/styles/_settings.scss
- src/assets/toolkit/styles/atoms/_links.scss
- src/assets/toolkit/styles/molecules/_all.scss
- src/assets/toolkit/styles/molecules/_react-tables.scss
- src/assets/toolkit/styles/molecules/_table-message.scss
- src/data/tables.yml
- src/materials/02-molecules/tables/table-applicants.html
- src/materials/02-molecules/tables/table-loading.html
- src/materials/02-molecules/tables/table-message.html
- src/views/layouts/default.html
See: /Molecules.html#tables.table-applicants
Use the tab key to navigate the table rows. You should see focus state on each row, then the application number for that row and then the status button for that row.
- Adding color maps for row status colors
- Adding variants for each status row with hover event
- Adding .auto-width class to control width of specific table cells, rt-td
Accessibility
- Adding role=table to class=ReactTable
- Adding role=rowgroup to class=rt-tr-group
- Adding role=row to class=rt-tr
- Adding tabindex=0 to class=rt-tr
JS Work that still needs to be done
- Each row has a hover event to indicate the row is clickable, but each row still needs to be made clickable to supplemental information
- Each row has a button that is tabable and clickable to indicate status …
> Table row status

- src/assets/toolkit/styles/_settings.scss
- src/assets/toolkit/styles/atoms/_button-groups.scss
- src/assets/toolkit/styles/atoms/_button.scss
- src/assets/toolkit/styles/atoms/_links.scss
- src/assets/toolkit/styles/atoms/_tables.scss
- src/assets/toolkit/styles/molecules/_lead-header.scss
- src/assets/toolkit/styles/molecules/_status-list.scss
- src/assets/toolkit/styles/molecules/_status-update.scss
- src/assets/toolkit/styles/organisms/_app-card.scss
- src/data/content.yml
- src/data/tables.yml
- src/data/toolkit.yml
- src/materials/01-atoms/tables/table--preferences.html
- src/materials/02-molecules/components/status-list.html
- src/materials/02-molecules/headers/lead-header--serif.html
- src/materials/02-molecules/tables/table--preferences.html
- src/materials/03-organisms/app-card-edit.html
- src/materials/03-organisms/app-card-tabs.html
See expandable table row example located as part of Confirmed Preferences:
https://sf-dahlia-pl-lap.herokuapp.com/08-leaseup/application.html
Pattern
molecules/tables/table-preferences
**Expandable Table Row**
- Adding .tr-expand pattern for expandable table rows
- .tr-expand: trigger row with edit link. has aria-expanded="true/false"
- .tr-expan-content: target row with nested panel. aria-hidden="true/false"
- .td-expand-nested: nested panel cell
- **js work still required.** Clicking Edit link in .tr-expand will add class="is-expanded" to .tr-expand and .tr-expand-content. Also changes  aria-expanded from "false" to "true" and aria-hidden from "true" to "false". Set .action-link inline-style to display:none.
- Adding .app-editable pattern for nested form container
- .app-editable: …
> Nested edit panel and updates based on user testing

- src/assets/toolkit/styles/molecules/_react-tables.scss
Reverts Exygy/sf-dahlia-pattern-library#74
> Revert "Adding styles to resolve application table issues"

- src/assets/toolkit/styles/molecules/_all.scss
- src/assets/toolkit/styles/molecules/_filter-row.scss
- src/assets/toolkit/styles/toolkit-lap.scss
- src/materials/01-atoms/forms/select--base.html
- src/materials/02-molecules/components/filter-row.html
- src/views/pages/08-leaseup/table.html
Adding component for table filters in lap
/molecules.html#components.filter-row
/08-leaseup/table.html
Adding a flexible container for 1 or more inputs and filter button.
- Has max width and right alignment
- Has medium and small screen breakpoints
> Adding markup and styles for filter-row component

- public/toolkit/styles/organisms/_splash.scss
Fixing order or css rules to resolve header height
> Swapping order of css rules to fix cascade

- public/toolkit/styles/molecules/_react-tables.scss
https://www.pivotaltracker.com/n/projects/1405352/stories/168173940/comments/206350083
> [#168173940] Remove opacity on text for is-invalid

- components/02-molecules/headers/banner-bar.html
- components/06-pages/01-basic-pages/home.html
- public/toolkit/styles/molecules/_all.scss
- public/toolkit/styles/molecules/_banner-bar.scss
- public/toolkit/styles/utilities/_print.scss
PR for the pattern-library portion of https://www.pivotaltracker.com/story/show/167303268 (will require some work on dahlia-web to implement fully). Includes new .banner-bar component in Molecules/Headers.
> Logo covers alert #167303268

- components/03-organisms/property-card--legacy.html
- components/03-organisms/property-card--sale.html
- components/03-organisms/property-card.html
- public/toolkit/styles/organisms/_property-card.scss
PR to fix https://www.pivotaltracker.com/story/show/170055626 includes changes to property card CSS and 3 property card HTML files.
> Overlapping date banners #170055626

- components/01-atoms/tables/pricing-table-hero--sale.html
- components/01-atoms/tables/pricing-table-hero.html
- components/03-organisms/property-card--legacy.html
- components/03-organisms/property-card--sale.html
- components/03-organisms/property-card.html
Fix https://www.pivotaltracker.com/story/show/169413027 via changing all property card h1 elements to h2, because a11y screen reader behavior.
> Property card a11y fixes #169413027

- components/01-atoms/tables/pricing-table-listing--newAMI.html
- components/01-atoms/tables/pricing-table-new--ownership.html
- components/01-atoms/tables/pricing-table-new--ownership_dual_parking.html
- components/01-atoms/tables/pricing-table-new--ownership_with_parking.html
- components/01-atoms/tables/pricing-table-new.config.json
- components/01-atoms/tables/pricing-table-new.html
- public/toolkit/styles/atoms/_tables.scss
Adding WIP PR to match up with work on https://github.com/Exygy/sf-dahlia-web/pull/1319
> 415 pricing table updates first pass #171215619

- components/01-atoms/tables/pricing-table-new--ownership.html
- components/01-atoms/tables/pricing-table-new--ownership_dual_parking.html
- components/01-atoms/tables/pricing-table-new--ownership_with_parking.html
- components/01-atoms/tables/pricing-table-new.html
- public/toolkit/styles/atoms/_tables.scss
adds vertical-align: top to th and td elements for tables with the top-align class.
> add new table.top-align class

- public/toolkit/styles/molecules/_version-bar.scss
This PR relates to [ticket #173071821](https://www.pivotaltracker.com/story/show/173071821)
> Show Version Bar on Mobile #173071821

- README.md
- deploy.sh
[#173314185](https://www.pivotaltracker.com/n/projects/1405352/stories/173314185)
> [Pattern library] Replace  master with main #173314185

- components/02-molecules/navigation/top-bar--account-tagalog.html
- public/toolkit/styles/molecules/_top-bar.scss
[#174106809](https://www.pivotaltracker.com/n/projects/1405352/stories/174106809)
Related Webapp PR: https://github.com/SFDigitalServices/sf-dahlia-web/pull/1403
> [pattern library] Fix navbar buttons for Filipino

- public/toolkit/styles/molecules/_react-tables.scss
DAH-157
I had increased the padding for the "offset right" column, but not the min-width so the status updated column was too small at some window sizes. This should fix it
> Fix width of status updated column DAH-157

- public/toolkit/styles/molecules/_filter-row.scss
- public/toolkit/styles/molecules/_inputs.scss
[DAH-568]
Also related to DAH-161
Needed to expand the search bar to fit all of the placeholder content
[DAH-568]: https://sfgovdt.jira.com/browse/DAH-568
> Add filter-group_item__large class [DAH-568]

- public/toolkit/styles/molecules/_status-history-sidebar.scss
[DAH-636](https://sfgovdt.jira.com/browse/DAH-636)
Updates for Status History to accommodate Rev3 changes.
> Updates for status item history [DAH-636]

- components/02-molecules/components/accordion-pricing-table--mobile.html
- components/02-molecules/components/accordion-pricing-table.html
- components/02-molecules/components/accordion.html
- public/toolkit/styles/molecules/_accordion-table.scss
- public/toolkit/styles/molecules/_accordion.scss
- public/toolkit/styles/molecules/_all.scss
- public/toolkit/styles/organisms/_page-accordion.scss
- public/toolkit/styles/utilities/_mixins.scss
- public/toolkit/styles/utilities/_spacing.scss
[DAH-659]: https://sfgovdt.jira.com/browse/DAH-659
Styles for the mobile and desktop pricing tables.
> [pattern library] Add pattern for pricing accordion [DAH-659]
