SFDigitalServices/sf-dahlia-pattern-library

src/assets/toolkit/styles/templates/_print.scss
@slowbot -- I just added `.top-bar` and `.version-bar` to hide from print, this allows the short form Review Summary to be printed nice and cleanly.
=> hide top-bar and version-bar in print.css

src/assets/toolkit/styles/templates/_print.scss
1. .ng-hide.show-for-print displays markup for angular elements
2. .print-only.show-for-print overwrites foundation css so that it hides content only if both classes are there
=> Update print styling. See details:

gulpfile.js, src/assets/fabricator/styles/partials/_layout.scss, src/assets/toolkit/styles/molecules/_message.scss, src/assets/toolkit/styles/toolkit-base.scss, src/assets/toolkit/styles/toolkit-lap.scss, src/views/account.html, src/views/application.html, src/views/atoms.html, src/views/browse.html, src/views/docs.html, src/views/eligibility.html, src/views/index.html, src/views/molecules.html, src/views/organisms.html, src/views/pages.html, src/views/property.html, src/views/samples.html, src/views/templates.html, src/views/utilities.html, src/views/utility-mixins.html
Creating three manifests for three different stylesheets to be out from the pattern library.
toolklt.scss is unchanged and reflects what we have today being consumed by the web app
toolkit-base.scss is only the base elements of the framework, including colors, forms, buttons etc
toolkit-lap.scss is base elements plus additional components that are used specifically in Leasing Agent Portal
Updated gulp file to run three watch and build tasks using the above naming convention. Curious to know your thoughts on naming of each of these tasks and filed and if we should try something different.
=> Features/compile separate styles #143063589

src/assets/toolkit/styles/molecules/_name-logo.scss, src/assets/toolkit/styles/molecules/_top-bar.scss, src/assets/toolkit/styles/organisms/_center-body.scss, src/assets/toolkit/styles/utilities/_grid.scss, src/assets/toolkit/styles/utilities/_spacing.scss
Created as part of implementing modifiers and variants for core layout components to LAP
- Adding full width component for topbar
- Limiting flex styles to parent li of navigation
- Adding an inner variant for inset app-container
- Adding active nav li state that was part of local styles in lap
- Adding additional spacing utility for 3x and 4x
There are a couple of modifications that I made that feel like they would benefit from a refactor of the core component.
- Should have added flex-nav as a modifier to the original component rather than baking into core
- Should add offset for version bar as a modifier
- Should add a layout rule for current default relationship between logo and nav widths
I recommend creating a story in an upcoming sprint to make these updates to PL and Dahlia
=> Adding styles for lap modifiers

src/assets/toolkit/styles/atoms/_button-groups.scss, src/assets/toolkit/styles/atoms/_button.scss, src/assets/toolkit/styles/molecules/_alerts.scss, src/assets/toolkit/styles/organisms/_modal.scss, src/materials/02-molecules/forms/alert-notice.html, src/materials/02-molecules/forms/button-stack.html, src/materials/02-molecules/forms/icon-input.html, src/materials/03-organisms/modal--message.html, src/materials/03-organisms/modal--small.html, src/materials/03-organisms/modal-alert-invert.html, src/materials/03-organisms/modal-alert.html, src/materials/03-organisms/modal.html, src/views/pages/07-modal/modal.html
- Adding .modal-footer element and .modal-button-group elements
- Moving .button-stack variant from .button to .button-group
- Adding .no-border button variant
- Adjusted spacing for .alert-box and .alert-notice
- Adding .alert and .alert-invert variants to .alert-notice
Requires changes to DAHLIA
- Change all alert-notice instances in DAHLIA that use ..alert to use .alert.invert
- Update all modal actions to use .modal-footer element and .modal-button-group elements
=> Modal styles based on LAP

src/assets/toolkit/styles/_settings.scss, src/assets/toolkit/styles/molecules/_all.scss, src/assets/toolkit/styles/molecules/_tabs-content.scss, src/assets/toolkit/styles/molecules/_tabs.scss, src/data/content.yml, src/data/menus.yml, src/data/type.yml, src/materials/02-molecules/components/tabs-content.html, src/materials/02-molecules/navigation/tabs--menu.html, src/materials/02-molecules/navigation/tabs.html, src/materials/03-organisms/tabs-section.html
- Customizing tab style to match design
- Adding tabs component markup for menubar
- ul role=menubar
- li role=none
- li a role=menuitem, tabindex="-1", 
- li.active a tabindex="0"
- Adding tabs component markup for tablist
- ul role=tablist
- li role=presentation
- li a role=tab, tabindex="-1",  aria-controls="#id"
- li.active a tabindex="0"
See
- http://localhost:3010/Molecules.html#navigation.tabs
- http://localhost:3010/Molecules.html#navigation.tabs--menu
- http://localhost:3010/Organisms.html#tabs-section
JS Requirements
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/menubar/menubar-1/menubar-1.html#
https://foundation.zurb.com/sites/docs/v/5.5.3/components/tabs.html#tabs-deeplink-3 (example at bottom of the page)
-  tabindex, aria-selected and .active: …
=> Tabs markup, accessibility and styles

src/assets/toolkit/styles/molecules/_name-logo.scss, src/assets/toolkit/styles/molecules/_top-bar.scss, src/assets/toolkit/styles/molecules/_translate-bar.scss, src/materials/02-molecules/headers/translate-bar.html, src/materials/02-molecules/navigation/top-bar--account.html, src/materials/02-molecules/navigation/top-bar--full.html, src/materials/02-molecules/navigation/top-bar--translation.html, src/materials/02-molecules/navigation/top-bar.html
Modifying navigation to use flexbox items as a modifier rather than the default setting to allow for reuse.
1. Isolated all flex-box attributes under a single utility class .has-flex-items
- added .has-flex-items to Webapp navigation .top-bar-section elements
- removed .no-max-width-items classes
2. Created a utility to control logo offset when .version-bar is present
- .is-offset-up
3. Created a utility to control logo size
- .is-tall
3. Fixed mobile spacing on translation menu
Webapp: https://github.com/Exygy/sf-dahlia-web/pull/1038
LAP: https://github.com/Exygy/sf-dahlia-lap/pull/28
Note these updates to master not lap-leaseup
=> Updating top bar navigation to use flex box as an option

src/assets/toolkit/styles/molecules/_directory-header.scss, src/assets/toolkit/styles/utilities/_lists.scss
Related to exygy/sf-dahlia-web#1130
This PR removes gratuitous spacing from the "Before applying" list when inside a content card.
=> [#162565298] Remove default margin on .numbered-list

src/assets/toolkit/styles/organisms/_app-card.scss
Related to Exygy/sf-dahlia-web#1176
- Visit `organisms.html#app-header` on a small browser window
- Confirm that you can scroll horizontally
=> Scroll long app-card navigation on small screens #164807951

.gitignore, components/02-molecules/headers/splash-header--small.html, public/toolkit/styles/organisms/_splash.scss
Adding classes for variants of splash header
- .hero-title .small for smaller text size
- .hero-header .narrow for additional padding on header text
- .hero-title_highlight to create underline text effect
=> Adding styles and classes for narrow splash header with highlighted text

package-lock.json, public/toolkit/styles/atoms/_tables.scss
Based on issue in https://github.com/Exygy/sf-dahlia-web/pull/1227
Pulled in this change to webapp and here's what rental listing details looks like:
Ownership column widths now:
=> Decrease width of listing detail availability column

public/toolkit/styles/molecules/_react-tables.scss
Previous work to remove opacity was in #97
Pattern lib has a weird thing going on with the cells with buttons, not sure how to fix it, but it's showing up for me on master (and several commits in the past) for me, but not showing up on the deployed pattern lib for some reason.
It looks OK on partners though when we pull it in:
@jrubenoff asking you to review this because I want to make sure that the css updates aren't too hacky!
=> Give invalid rows alert-tint background #168173940

components/01-atoms/forms/checkbox.html, public/toolkit/styles/atoms/_button.scss, public/toolkit/styles/atoms/_forms.scss, public/toolkit/styles/atoms/_links.scss, public/toolkit/styles/molecules/_inputs.scss
[Ticket](https://www.pivotaltracker.com/story/show/168041979)
Corresponding webapp pr: https://github.com/Exygy/sf-dahlia-web/pull/1263
- Button segments are not keyboard accessible, follow-up ticket: [#168589930](https://www.pivotaltracker.com/story/show/168589930)
- Language links at the top are missing top and bottom borders, bottom of nav menu links are also missing the highlight, follow-up ticket: [#168527541](https://www.pivotaltracker.com/story/show/168527541)
1. Go to to the [review app](https://sf-dahlia-pl-keyboard-focus.herokuapp.com/), or run the pattern lib locally
1. Go to the [buttons page](https://sf-dahlia-pl-keyboard-focus.herokuapp.com/components/detail/button-guidelines.html) and verify that when you tab over the buttons they have the new super-visible focus border
1. …
=> Improve keyboard focus accessibility #168041979

components/02-molecules/stats/stats-toggle--one-br.html, components/02-molecules/stats/stats-toggle.html, public/toolkit/styles/atoms/_button.scss, public/toolkit/styles/molecules/_stats-list.scss
Review app: https://sf-dahlia-pl-unit-tab-focus.herokuapp.com/
Relevant component: https://sf-dahlia-pl-unit-tab-focus.herokuapp.com/components/detail/stats-toggle--default
I wasn't able to get it to be tabbable in the pattern library, but you can check that the focus is right by modifying the css
=> Add focus to unit features accordion #168041979

components/01-atoms/tables/pricing-table-listing--sale-with-no-parking.html, components/01-atoms/tables/pricing-table-listing--sale-with-parking-lease.html, components/01-atoms/tables/pricing-table-listing--sale-with-parking.html, components/01-atoms/tables/pricing-table-listing--sro.html, components/01-atoms/tables/pricing-table-listing.html, public/toolkit/styles/atoms/_tables.scss
Fix an issue with the formatting of the pricing table when the user selects Spanish as the site language: https://www.pivotaltracker.com/story/show/170459019
This required altering a style that depended on a data attribute that itself is translated, so when a non-English language is selected, the style was not applied. This PR contains the CSS and markup changes needed to remove this dependency.
=> Bugs/spanish pricing table formatting #170459019

components/01-atoms/tables/pricing-table-listing--sale-with-no-parking.html, components/01-atoms/tables/pricing-table-listing--sale-with-parking-lease.html, components/01-atoms/tables/pricing-table-listing--sale-with-parking.html, components/01-atoms/tables/pricing-table-listing--sro.html, components/01-atoms/tables/pricing-table-listing.html, components/03-organisms/content-section.html, public/toolkit/styles/atoms/_tables.scss, public/toolkit/styles/utilities/_spacing.scss
Ensure that content-section feature table markup matches that in dahlia-web as of PR https://github.com/Exygy/sf-dahlia-web/pull/1308 – this widens the title div to accommodate long words as found in non-English languages, especially Spanish.
=> Bugs/feature table formatting problem #170433148

components/01-atoms/tables/pricing-table-new--ownership.html, components/01-atoms/tables/pricing-table-new--ownership_dual_parking.html, components/01-atoms/tables/pricing-table-new--ownership_with_parking.html, components/01-atoms/tables/pricing-table-new.html, public/toolkit/styles/atoms/_tables.scss
Replaces pricing table styles for nested tables that depend on data-th attributes with a class that is added to the td that wraps the nested tables.
=> Replace pricing table data th styles

public/toolkit/styles/atoms/_tables.scss
add ::before content to <small> elements in pricing tables at smallest viewport size rather than using margin-left.
=> fix pricing table spacing for <small> elements on mobile

components/01-atoms/tables/pricing-table-new.html, public/toolkit/styles/atoms/_tables.scss
To fix ticket [#172594819](https://www.pivotaltracker.com/n/projects/1405352/stories/172594819) we need to make the rent column a nested table
in the same way the income column is. This change adds the styles
necessary for that.
Webapp pr: https://github.com/SFDigitalServices/sf-dahlia-web/pull/1354
The nested table in the rent column includes a whitout-ed header with the word "rent" so it is read out in jaws. See [this conversation](https://sfdigitalservices.slack.com/archives/CCHRVN7AB/p1592254070005200) where Christina says the existing solution doesn't work in windows.
=> Add class for table-nested-rent #172594819

components/01-atoms/tables/pricing-table-new--ownership.html, components/01-atoms/tables/pricing-table-new--ownership_dual_parking.html, components/01-atoms/tables/pricing-table-new--ownership_with_parking.html, components/01-atoms/tables/pricing-table-new.config.json, components/01-atoms/tables/pricing-table-new.html, public/toolkit/styles/atoms/_tables.scss
Separate the income labels for small and large devices so that on large
devices the label can wrap properly based on cell width.
I decided to make the units cell fixed-width because before the width was based on the longest text in the cell, which used to always be the word "available" so this column always had the same width for every table on the page. Now, since the income text is part of the cell and is really variable, these cell widths look inconsistent across the page unless they are set to a fixed value.
=> [Pattern] Fix income label overlap #172562390

components/01-atoms/tables/pricing-table-new--ownership.html, components/01-atoms/tables/pricing-table-new--ownership_dual_parking.html, components/01-atoms/tables/pricing-table-new--ownership_with_parking.html, components/01-atoms/tables/pricing-table-new.html, public/toolkit/styles/atoms/_tables.scss, public/toolkit/styles/utilities/_type.scss
[#173618329](https://www.pivotaltracker.com/n/projects/1405352/stories/173618329)
This change makes it so that the AMI tiers table switches to the "mobile view" when at large screen size.
I tried to make sure not to touch other tables with this change.
=> [Pattern Library] Fix squished sale listings #173618329

components/01-atoms/tables/pricing-table-new--ownership.html, components/01-atoms/tables/pricing-table-new--ownership_dual_parking.html, components/01-atoms/tables/pricing-table-new--ownership_with_parking.html, components/01-atoms/tables/pricing-table-new.html, public/toolkit/styles/atoms/_tables.scss
Now that we're not using the class "whiteout" to hide subheaders on DAHLIA, we can remove it from the pattern library.
Ticket: https://www.pivotaltracker.com/story/show/173712407
Review app: https://sf-dahlia-pl-remove-whiteout.herokuapp.com/
Review instructions:
Check that Patterns for [rental](https://sf-dahlia-pl-remove-whiteout.herokuapp.com/components/detail/pricing-table-new--default.html) and [sales](https://sf-dahlia-pl-remove-whiteout.herokuapp.com/components/detail/pricing-table-new--ownership_dual_parking.html) tables look as expected:
- subheaders such as "minimum" and "maximum" are no longer whited out
- "RENT" subheader is still present if you highlight the text, but is not visible
=> Remove now-unused whiteout class #173712407

components/01-atoms/icons/icon-plus-minus.html, components/02-molecules/components/accordion-plus-minus.html, components/02-molecules/components/accumulator.html, public/toolkit/styles/molecules/_accordion.scss, public/toolkit/styles/molecules/_accumulator.scss
Polish the demographics styles, when adding the accordion to webapp I found some things that are not the same as the designs.
=> Features/demographics polish #173303363

public/toolkit/styles/atoms/_tables.scss
Fix overlapping headers and cells by:
- Setting the max width of header and cells to 50%
- Add a padding of 1rem between th and td so text never touches
- Set small text to be inline-block so that it wraps to a new line before breaking other text
Notice that the headers get cut off, this is because their height isn't part of the parent height calculation. This is a lot harder to fix, as removing position: absolute from the header has ripple effects that require lots of other changes. I recommend we merge this fix as is and either create a separate ticket to fix this or we wait until the re-write.
=> Fix mobile directory view #173346911

components/02-molecules/components/accordion-plus-minus.html, public/toolkit/styles/molecules/_accordion.scss
- Add padding between text and text input
- Add padding between multiple text inputs
- Don't allow text input to go past the edge of the accordion
=> Features/indigenous specific group #173951931

public/toolkit/styles/molecules/_top-bar.scss
[this pr](https://github.com/SFDigitalServices/sf-dahlia-pattern-library/pull/134/files) broke the partners navbar because width was set to 100% and the elements weren't justified to the correct side. This created a separate partners class and partners-left-justified class to fix these issues.
=> [Pattern library] Fix partners navbar

components/03-organisms/modal--status-open.html, public/toolkit/styles/molecules/_dropdowns.scss
The pattern library example uses classes very differently to how they're used in Partners.
This change:
- Converts the pattern library example to use the classes that are used in partners
- Fixes the dropdown so it doesn't need to be manually positioned in the react code. Now instead of adding margin to the dropdown-button, you'd add it to the `dropdown` div instead. That way the absolutely positioned dropdown appears directly under the dropdown-button, not under the dropdown-button + the button's margin.
Affect on partners: Allows us to remove any custom positioning logic, dropdown is now positioned correctly no matter what, and the button can have whatever margin it wants, as long as it's added to the `dropdown` component, not the `dropdown-button` component.
Affect on webapp: None, …
=> Fix dropdown patterns

components/02-molecules/components/status-history-sidebar.html, public/toolkit/styles/molecules/_status-history-sidebar.scss
Jira ticket: [#DAHLIAFE-25](https://sfgovdt.jira.com/browse/DAHLIAFE-25?atlOrigin=eyJpIjoiMDFlNmQ2NDczNTc5NGQwYTg2ZjNiZjQ4YzBiMTIzYzYiLCJwIjoiaiJ9)
[Designs](https://www.figma.com/file/FFaD5ZlsL9QzpTsA8yP7iI/scooting-partners-supp-app-170930954?node-id=159%3A0)
When I added the pattern for the sidebar I missed that status items can have substatuses, that should show as slightly gray-er text above the comment text.
=> Add substatus text class #DAHLIAFE-25

public/toolkit/styles/molecules/_status-history-sidebar.scss
Partners implementation issue [#DAHLIAFE-37](https://sfgovdt.jira.com/browse/DAHLIAFE-37?atlOrigin=eyJpIjoiYWJkMDY2MWVlNzM4NDE3NmIxYjhjYzBlOGQ0ZTNlMzkiLCJwIjoiaiJ9)
Pattern library issue [#DAHLIAFE-25](https://sfgovdt.jira.com/browse/DAHLIAFE-25?atlOrigin=eyJpIjoiYWJkMDY2MWVlNzM4NDE3NmIxYjhjYzBlOGQ0ZTNlMzkiLCJwIjoiaiJ9)
While implementing the sidebar components, I found that my [recent change](https://github.com/SFDigitalServices/sf-dahlia-pattern-library/pull/137) to fix dropdown patterns broke the way we're using dropdown buttons in the sidebar. This fixes the issue by setting the button width on the .dropdown div, not the child button.
=> Set width on dropdown item, not child button #DAHLIAFE-25

components/01-atoms/pills/status-pill.html, components/02-molecules/components/status-history-sidebar--with-show-all-link.html, components/02-molecules/components/status-history-sidebar--with-show-recent-link.html, components/02-molecules/components/status-history-sidebar.html, public/toolkit/styles/atoms/_pills.scss, public/toolkit/styles/molecules/_status-history-sidebar.scss
Jira ticket: [[#DAH-37](https://sfgovdt.jira.com/browse/DAH-37)]
We don't actually need the separate `pill-text` divs, we can just add the text styles to the `status-pill` parent. Also, change the class names to be separate classes for the pill and styling.
I also moved the sidebar component styling outside of the sidebar column, since while building the components I realized you should be able to have the sidebar styled properly whether or not it's in a column.
=> [DAH-37] Simplify pill styling

components/01-atoms/tables/table--preferences.html, public/toolkit/styles/atoms/_forms.scss, public/toolkit/styles/atoms/_tables.scss, public/toolkit/styles/organisms/_app-card.scss
This PR:
- Updates form note to make it tiny and not-bold
- Makes app card h3 semi-bold
- Adds class to use to have the preferences and rental assistance table scroll when there's overflow
=> Update styles for new supplemental application layout  [DAH-36]

public/toolkit/styles/molecules/_status-history-sidebar.scss
[DAH-37]
- reduce the padding on top of the status history at small screen sizes
- This is because the element above has its own bottom margin, they should add to 3rem.
- Remove percent height on the sidebar column. This is so that we can use flex's align-items: stretch to make all children stretch to fill the parent.
- Add side padding to the sidebar-content at small screen sizes. This is the same padding the content-sections have
- Shrink bottom padding on the show/hide link at small screen sizes to match designs
[DAH-37]: https://sfgovdt.jira.com/browse/DAH-37
=> Polish sidebar padding [DAH-37]

public/toolkit/styles/organisms/_app-card.scss
DAH-90
This PR:
1. Renames app-editable to be inline modal
1. Adds a background of white if there's an inline modal inside of an inline modal. 
See this image of this in action in partners
=> Add background white for nested inline modal DAH-90

public/toolkit/styles/organisms/_app-card.scss
Fixes rental assistance issue where inline modal was not taking up 100% of available width https://github.com/SFDigitalServices/sf-dahlia-lap/pull/394
=> Update inline modal to give it a width of 100%

public/toolkit/styles/molecules/_dropdowns.scss
This PR makes the hover state for dropdowns a bit more visible.
Change was implemented in partners in https://github.com/SFDigitalServices/sf-dahlia-lap/pull/408/files
Before: 
After:
The blue styling for selected is coming from the Dropdown component. 
DAH-124
=> Update hover background color for Dropdowns

public/toolkit/styles/atoms/_forms.scss
Fixes a text issue with [DAH-142]
The text style was 1px off, this adds a "small" style that sets the text to the correct value.
[DAH-142]: https://sfgovdt.jira.com/browse/DAH-142
=> Add form note small style [DAH-142]

components/01-atoms/forms/input-search.html, public/toolkit/styles/molecules/_inputs.scss
DAH-159
This PR adds a pattern for the search input along with some styles to get it to work.
The pattern here doesn't have the interactions that we'll have in Partners. Instead of only showing the icon when there's text present, this pattern just shows the case with the clear icon present. The clear icon is also not functional in this example. 
To QA:
- Review the input search pattern locally: http://localhost:3001/components/detail/input-search
=> Add pattern for search input DAH-159

components/01-atoms/buttons/buttons.config.yml, public/toolkit/styles/atoms/_button.scss
Patterns for [DAH-568]
padding extra needed for apply and clear filters buttons, tertiary-inverse is for apply button when there are no new changes.
[DAH-568]: https://sfgovdt.jira.com/browse/DAH-568
=> [Pattern library] Add tertiary-inverse and button.padding-extra patterns [DAH-568]

public/toolkit/styles/atoms/_button.scss, public/toolkit/styles/molecules/_filter-row.scss, public/toolkit/styles/molecules/_react-tables.scss
[DAH-162]
- Add tight-padding-vertical class for buttons (for the tiny status button)
- Add button-icon-only class for buttons without any border, just an icon. This class mostly just re-sets all of the style defaults we have on buttons
- Add padding to filter row (only used in application page)
- lots of cell styling changes
[DAH-162]: https://sfgovdt.jira.com/browse/DAH-162
=> [Pattern library] Update table styling [DAH-162]

public/toolkit/styles/molecules/_dropdowns.scss, public/toolkit/styles/molecules/_filter-row.scss, public/toolkit/styles/molecules/_inputs.scss
DAH-564
This PR:
1. Removes unnecessary margin from the dropdown button class (maybe should check the unit dropdown actually)
1. Adds a no-margin class that can be added to the checkbox + label combo to get rid of the right margin on checkboxes
=> Fix checkbox and dropdown button styling DAH-564

public/toolkit/styles/molecules/_status-history-sidebar.scss
Discovered while working on DAH-564
Before the status update buttons could be different heights if one was multiline and the other was not. This change makes it so they are always the same height.
Note that in this screenshot, the processing button is taller even though processing isn't wrapped to multiple lines. Before this change, the buttons would be different sizes
=> Fix status update buttons [DAH-564]
